language: java
before_install:
  - sudo ant download-ivy
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: ant test -Dskip.download=true
jdk:
#  - oraclejdk8
  - oraclejdk7
- openjdk7
